CREATE TABLE users (
	id	MEDIUMINT NOT NULL AUTO_INCREMENT,
	login VARCHAR(60) NOT NULL,
	mail VARCHAR(255) NOT NULL,
	pw varchar(255) NOT NULL,
	fablab varchar(60) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE fablab (
	nom VARCHAR(255) NOT NULL,
	adresse VARCHAR(255) NOT NULL,
	ville VARCHAR(255) NOT NULL,
	cp VARCHAR(255) NOT NULL,
	pays VARCHAR(255) NOT NULL,
	mail VARCHAR(255) NOT NULL,
	PRIMARY KEY(nom)	
);

ALTER TABLE users ADD CONSTRAINT FKusers FOREIGN KEY (fablab) REFERENCES fablab (nom);